[[constraint]]
  name = "github.com/blang/semver"
  version = "=3.5.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"
